# Generated by Django 3.0.7 on 2020-06-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medium',
        ),
    ]
