# Generated by Django 3.0.7 on 2020-06-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0007_auto_20200606_1017'),
        ('posts', '0003_remove_post_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mediums.Medium'),
            preserve_default=False,
        ),
    ]
