# Generated by Django 3.0.7 on 2020-06-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='mediums.Medium')),
            ],
        ),
    ]
