# Generated by Django 3.0.7 on 2020-06-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='medium',
        ),
        migrations.AddField(
            model_name='favourite',
            name='medium',
            field=models.ManyToManyField(related_name='favourites', to='mediums.Medium'),
        ),
    ]
