# Generated by Django 3.0.7 on 2020-06-07 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourites', '0002_auto_20200606_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='medium',
        ),
        migrations.AddField(
            model_name='favourite',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='favourites', to='mediums.Medium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
