# Generated by Django 3.0.7 on 2020-06-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_favourites',
        ),
    ]
