# Generated by Django 3.0.7 on 2020-06-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_favourites',
            field=models.ManyToManyField(related_name='jwt_auth', to='favourites.Favourite'),
        ),
    ]
