# Generated by Django 3.0.7 on 2020-06-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_auto_20200606_2104'),
        ('jwt_auth', '0002_user_user_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_favourites',
        ),
        migrations.AddField(
            model_name='user',
            name='user_favourites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jwt_auth', to='favourites.Favourite'),
        ),
    ]
