# Generated by Django 3.0.7 on 2020-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('image', models.CharField(max_length=400)),
                ('video', models.CharField(blank=True, max_length=400, null=True)),
                ('info', models.CharField(max_length=500)),
                ('price', models.FloatField(blank=True, null=True)),
                ('start_date_end_date', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
