# Generated by Django 3.0.7 on 2020-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='start_date_end_date',
        ),
        migrations.AddField(
            model_name='medium',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medium',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
