# Generated by Django 3.0.7 on 2020-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_medium'),
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='reviews',
            field=models.ManyToManyField(related_name='mediums', to='reviews.Review'),
        ),
    ]
