# Generated by Django 3.0.7 on 2020-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='category',
            new_name='categories',
        ),
    ]
