# Generated by Django 3.0.7 on 2020-06-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0002_medium_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='reviews',
        ),
    ]
