# Generated by Django 3.0.7 on 2020-06-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0002_auto_20200605_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='categories',
            new_name='category',
        ),
    ]
