# Generated by Django 3.0.7 on 2020-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0002_auto_20200605_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
