# Generated by Django 3.0.7 on 2020-06-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0003_auto_20200605_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='date_posted',
        ),
    ]
