# Generated by Django 3.0.7 on 2020-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0003_auto_20200605_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='art_gallery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medium',
            name='art_gallery_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
