# Generated by Django 3.0.7 on 2020-06-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_medium'),
        ('mediums', '0004_remove_medium_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mediums', to='posts.Post'),
            preserve_default=False,
        ),
    ]
