# Generated by Django 3.0.7 on 2020-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0004_auto_20200605_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='info',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medium',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
