# Generated by Django 3.0.7 on 2020-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_medium'),
        ('mediums', '0005_medium_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='post',
        ),
        migrations.AddField(
            model_name='medium',
            name='posts',
            field=models.ManyToManyField(related_name='mediums', to='posts.Post'),
        ),
    ]
