# Generated by Django 3.0.7 on 2020-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0005_auto_20200605_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
