# Generated by Django 3.0.7 on 2020-06-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0007_auto_20200606_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='post',
        ),
    ]
