# Generated by Django 3.0.7 on 2020-06-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0003_remove_medium_reviews'),
        ('reviews', '0003_auto_20200609_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mediums.Medium'),
            preserve_default=False,
        ),
    ]
